name: publish to nuget
on:
  push:
    branches:
      - release/1.0.x
      - release/2.x
      - release/3.x
      - release/4.x
      - release/5.x
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '6.0.x'
    
      - name: Run tests for Core
        run: |
          cd ./tests/Pipaslot.Mediator.Tests/
          dotnet test
    
      - name: Run tests for HTTP
        run: |
          cd ./tests/Pipaslot.Mediator.Http.Tests/
          dotnet test
      
      # Publish
      - name: publish Pipaslot.Mediator
        id: publish_nuget_core
        continue-on-error: true
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Pipaslot.Mediator/Pipaslot.Mediator.csproj          
          PACKAGE_NAME: Pipaslot.Mediator
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish Pipaslot.Mediator.Http
        id: publish_nuget_http
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Pipaslot.Mediator.Http/Pipaslot.Mediator.Http.csproj          
          PACKAGE_NAME: Pipaslot.Mediator.Http
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 