name: publish to nuget
on:
  push:
    branches:
      - release/1.0.x
      - release/2.x
      - release/3.x
      - release/4.x
      - release/5.x
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '6.0.x'
    
      - name: Run tests for Core
        run: |
          cd ./tests/Pipaslot.Mediator.Tests/
          dotnet test
    
      - name: Run tests for HTTP
        run: |
          cd ./tests/Pipaslot.Mediator.Http.Tests/
          dotnet test
      
      # Publish      

      - name: Pack Core
        run: dotnet pack Pipaslot.Mediator/Pipaslot.Mediator.csproj -c Release -o ./packed/

      - name: Pack Http
        run: dotnet pack Pipaslot.Mediator.Http/Pipaslot.Mediator.Http.csproj -c Release -o ./packed/

      - name: Publish
        run: dotnet nuget push ./packed/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate