name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Publish
      - name: publish Pipaslot.Mediator
        id: publish_nuget_core
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Pipaslot.Mediator/Pipaslot.Mediator.csproj          
          PACKAGE_NAME: Pipaslot.Mediator
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish Pipaslot.Mediator.Http
        id: publish_nuget_client
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Pipaslot.Mediator.Http/Pipaslot.Mediator.Http.csproj          
          PACKAGE_NAME: Pipaslot.Mediator.Http
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}  

      - name: publish Pipaslot.Mediator.Client
        id: publish_nuget_client
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Pipaslot.Mediator.Client/Pipaslot.Mediator.Client.csproj          
          PACKAGE_NAME: Pipaslot.Mediator.Client
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}      
      
      - name: publish Pipaslot.Mediator.Server
        id: publish_nuget_server
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Pipaslot.Mediator.Server/Pipaslot.Mediator.Server.csproj          
          PACKAGE_NAME: Pipaslot.Mediator.Server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}